"""Códigos RBAC da API PAC Qualidade (agente e escrita transacional)."""

QUALITY_ACTION_PLANS_ACCESS = "quality-action-plans.access"
QUALITY_ACTION_PLANS_READ = "quality-action-plans.read"
QUALITY_ACTION_PLANS_WRITE = "quality-action-plans.write"
QUALITY_ACTION_PLANS_MANAGE = "quality-action-plans.manage"

QUALITY_ACTION_PLANS_READ_PERMISSIONS = [
    QUALITY_ACTION_PLANS_ACCESS,
    QUALITY_ACTION_PLANS_READ,
    QUALITY_ACTION_PLANS_MANAGE,
]
QUALITY_ACTION_PLANS_WRITE_PERMISSIONS = [
    QUALITY_ACTION_PLANS_ACCESS,
    QUALITY_ACTION_PLANS_WRITE,
    QUALITY_ACTION_PLANS_MANAGE,
]
